#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

#bl2bids

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

# make output directory
mkdir -p out_dir

#python main.py
singularity exec docker://brainlife/mne:0.23dev python3 main.py


