#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

#bl2bids

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

# make output directory
mkdir -p out_dir
mkdir -p out_dir2

#python main.py
singularity exec docker://brainlife/mne:0.23dev python3 main.py

# Store PSD plot with alpha peak on product.json
cat << EOF > product.json
{
    "brainlife": [
       { 
           "type": "image/png", 
	   "name": "mne defaults PSD plot",
           "base64": "$(base64 -w 0 out_dir2/psd_mne.png)"
       },
       { 
           "type": "image/png", 
	   "name": "computed PSD",
           "base64": "$(base64 -w 0 out_dir2/psd_computed.png)"
       }
]
}
EOF



